image: docker:stable

services:
    - docker:dind

stages:
    - Build and static QA
    - Dynamic QA
    - Release



Check linting:
  stage: Build and static QA
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - apk add make
    - ARGS="--check" make lint

Unit Tests:
    stage: Dynamic QA
    before_script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
        - echo "all ok"
    