stages:
    - QA
    - Release

Check linting:
  image: divio/lint
  stage: QA
  script:
    - cd /builds/divio/cloud/cli/ && LINT_FOLDER_PYTHON=divio_cli /bin/lint --check

Unit Tests:
    stage: QA
    image: divio/base:1.1-py3.6-alpine3.12
    script:
        - apk add git 
        - pip install setuptools_scm pytest
        - pip install -r requirements.txt
        - pytest

Release Tag:
    stage: Release
    image: divio/base:1.1-py3.6-alpine3.12
    script:
        - apk add python3-dev build-base libffi-dev openssl-dev git
        - pip install twine check-manifest setuptools_scm
        - pip install -r requirements.txt
        # Install the package in develop mode so setuptools_scm can retrieve 
        # the new version.
        - python setup.py sdist bdist_wheel
        - twine check dist/*
        - check-manifest
        - twine upload --repository testpypi -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
    only:
        - tags
