stages:
    - QA
    - Release

Check linting:
  image: divio/lint
  stage: QA
  variables: 
    LINT_FOLDER_PYTHON: divio_cli 
  script:
    - /bin/lint --check

Unit Tests:
    stage: QA
    image: themattrix/tox
    script: tox
    artifacts:
      reports:
        cobertura: coverage.xml
        junit: junit-testreport-*.xml

Check Manifest:
  stage: QA
  image: python:3-alpine
  script:
      - apk add git
      - pip install check-manifest
      - check-manifest

Release Tag:
    stage: Release
    image: python:3-alpine
    script:
        - apk add python3-dev build-base libffi-dev openssl-dev git
        - pip install twine setuptools_scm
        # Install the package in develop mode so setuptools_scm can retrieve 
        # the new version.
        - python setup.py sdist bdist_wheel
        - twine check dist/*
        - twine upload --repository testpypi -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
    only:
        - tags
