image: docker:stable

services:
    - docker:dind

stages:
    - QA



Check linting:
  stage: QA
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - apk add make
    - ARGS="--check" make lint

Unit Tests:
    stage: QA
    before_script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
        - pip install pytest==6.1
        - pytest
    