image: docker:stable

services:
    - docker:dind

stages:
    - QA
    - Release to PyPI



Check linting:
  stage: QA
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - apk add make
    - ARGS="--check" make lint

Unit Tests:
    stage: QA
    before_script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
        - apk add py-pip
        - pip install pytest==6.1
        - pip install -r requirements.txt
        - pytest

Release Tag:
    stage: Release to PyPI
    script:
        - apk add py-pip
        - pip install twine
        - python setup.py sdist bdist_wheel
#    only:
#        - tags
