
services:
    - docker:dind

stages:
    - QA
    - Release to PyPI



Check linting:
  image: docker:stable
  stage: QA
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - apk add make
    - ARGS="--check" make lint

Unit Tests:
    stage: QA
    script:
        - apt-get update -qy
        - apt-get install -y python-dev python-pip
        - pip install -r requirements.txt
        - pytest

Release Tag:
    stage: Release to PyPI
    script:
        - apk add py-pip
        - pip install twine
        - python setup.py sdist bdist_wheel
#    only:
#        - tags
