stages:
    - QA
    - Release to PyPI



Check linting:
  image: docker:stable
  services:
    - docker:dind
  stage: QA
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - apk add make
    - ARGS="--check" make lint

Unit Tests:
    stage: QA
    image: divio/base:1.1-py3.6-alpine3.12
    script:
        - apk add git 
        - pip install -r requirements.txt
        - pytest

Release Tag:
    stage: Release to PyPI
    image: divio/base:1.1-py3.6-alpine3.12
    script:
        - apk add python3-dev build-base libffi-dev openssl-dev 
        - pip install twine
        - python setup.py sdist bdist_wheel
#    only:
#        - tags
