[tool.isort]
known_project="divio_cli"
sections="FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,PROJECT,LOCALFOLDER"
multi_line_output=3
line_length = 79
lines_after_imports = 2
lines_between_types = 0
atomic = true
order_by_type = true
include_trailing_comma = true
use_parentheses = true
not_skip="__init__.py"
