[tool.isort]
known_project="divio_cli"
sections="FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,PROJECT,LOCALFOLDER"

[tool.check-manifest]
ignore = ["tox.ini", "requirements.in", "requirements-windows.in", "Makefile", ".gitlab-ci.yml"]


[tool.setuptools_scm]
