version: 2

jobs:
  python-linux:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./scripts/build-unix.sh
  python-osx:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Setup brew/virtualenv
          command: | 
            brew update
            brew upgrade python
            pip3 install virtualenv
            virtualenv env -p python3
      - run:
          name: Run Tests
          command: |
            source env/bin/activate
            ./scripts/build-unix.sh

workflows:
  version: 2
  build:
    jobs:
        - python-linux
        - python-osx
